/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace BusinessObjects
{
    public enum EnumExpertValueScope
    {
        GlobalScope = 0,
        ExpertScope = 1,
        OrderScope = 3
    }
}