/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace BusinessObjects.BusinessObjects;

/// <summary>
///     You can define enums, which are just 32 bit integers. Values are optional
///     and start at 1 if not supplied, C style again.
/// </summary>
public enum EnumExpertValueType
{
    ValueUndefined = 0,
    ValueInteger = 1,
    ValueShort = 2,
    ValueDouble = 3,
    ValueString = 4,
    ValueBool = 5
}
