/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace BusinessObjects.BusinessObjects;
public enum SignalFlags
{
    Auto = 0,
    Server = 1,
    Expert = 2,
    Cluster = 3,
    Terminal = 4,
    AllTerminals = 5
}